# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8370fd2d95b42d3399d40d42f02c428a"
name = "OrderStatus"
application_url = "https://order-delivery-exporter.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_orders,read_shipping"

[auth]
redirect_urls = [
  "https://order-delivery-exporter.vercel.app/auth/callback",
  "https://order-delivery-exporter.vercel.app/auth/shopify/callback",
  "https://order-delivery-exporter.vercel.app/api/webhooks"
]
